import csv
import re
from pathlib import Path


EXACT_REPLACEMENTS = {
    "Aix-Marseille Université Centre PsyClé França": "Aix-Marseille Université (AMU)",
    "Bahia State University": "Universidade do Estado da Bahia (UNEB)",
    "CEFET-MG": "Centro Federal de Educação Tecnológica de Minas Gerais (CEFET-MG)",
    "CEFET/RJ": "Centro Federal de Educação Tecnológica Celso Suckow da Fonseca (CEFET/RJ)",
    "CENTRO UNIVERSITÁRIO UNIFTEC": "Centro Universitário UNIFTEC (UNIFTEC)",
    "CIn-UFPE": "Universidade Federal de Pernambuco (UFPE)",
    "Centro Universitário UNIFTEC": "Centro Universitário UNIFTEC (UNIFTEC)",
    "Centro Universitário de Brusque - UNIFEBE": "Centro Universitário de Brusque (UNIFEBE)",
    "Centro universitário Mauricio de Nassau": "Centro Universitário Maurício de Nassau (UNINASSAU)",
    "Centro Federal de Educação Tecnológica Celso Suckow da Fonseca": "Centro Federal de Educação Tecnológica Celso Suckow da Fonseca (CEFET/RJ)",
    "Centro Federal de Educação Tecnológica de Minas Gerais": "Centro Federal de Educação Tecnológica de Minas Gerais (CEFET-MG)",
    "Escola de Artes Ciências e Humanidades - Universidade de São Paulo": "Universidade de São Paulo (USP)",
    "Federal University Of Ceara Brazil": "Universidade Federal do Ceará (UFC)",
    "Federal University at Sao Paulo - UNIFESP": "Universidade Federal de São Paulo (UNIFESP)",
    "Federal University of Amazonas": "Universidade Federal do Amazonas (UFAM)",
    "Federal University of Campina Grande": "Universidade Federal de Campina Grande (UFCG)",
    "Federal University of Ceará": "Universidade Federal do Ceará (UFC)",
    "Federal University of Espírito Santo": "Universidade Federal do Espírito Santo (UFES)",
    "Federal University of Juiz de Fora": "Universidade Federal de Juiz de Fora (UFJF)",
    "Federal University of Lavras": "Universidade Federal de Lavras (UFLA)",
    "Federal University of Paraiba": "Universidade Federal da Paraíba (UFPB)",
    "Federal University of Rio Grande (FURG)": "Universidade Federal do Rio Grande (FURG)",
    "Federal University of Rio de Janeiro": "Universidade Federal do Rio de Janeiro (UFRJ)",
    "Federal University of São João del Rei": "Universidade Federal de São João del-Rei (UFSJ)",
    "Federal University of Uberlândia": "Universidade Federal de Uberlândia (UFU)",
    "Federal University of Western Pará": "Universidade Federal do Oeste do Pará (UFOPA)",
    "Federal University of the State of Rio de Janeiro (UNIRIO)": "Universidade Federal do Estado do Rio de Janeiro (UNIRIO)",
    "Florida Institute of Technology": "Florida Institute of Technology (FIT)",
    "Harvard University": "Harvard University",
    "ICMC-USP": "Universidade de São Paulo (USP)",
    "IF Sertão PE - Campus Petrolina": "Instituto Federal do Sertão Pernambucano (IFSertãoPE)",
    "IFAL": "Instituto Federal de Alagoas (IFAL)",
    "IFAL - -- Select Country": "Instituto Federal de Alagoas (IFAL)",
    "IFCE": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "IFCE - Campus Crato": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "IFCE - Instituto Federal de Educação Ciência e Tecnologia do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "IFCE - Instituto Federal de Educação, Ciência e Tecnologia do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "IFMA": "Instituto Federal de Educação Ciência e Tecnologia do Maranhão (IFMA)",
    "IFNMG": "Instituto Federal de Educação Ciência e Tecnologia do Norte de Minas Gerais (IFNMG)",
    "IFRS": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "IFRS - Campus Porto Alegre": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "IFRS - Instituto Federal de Educação Ciência e Tecnologia do RS": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "IFS": "Instituto Federal de Sergipe (IFS)",
    "IFsul": "Instituto Federal Sul-rio-grandense (IFSul)",
    "INES": "Instituto Nacional de Educação de Surdos (INES)",
    "INSTITUTO FEDERAL DO CEARÁ-IFCE": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "INSTITUTO FEDERAL DO PARANÁ": "Instituto Federal do Paraná (IFPR)",
    "ITA - Instituto Tecnológico de Aeronáutica": "Instituto Tecnológico de Aeronáutica (ITA)",
    "Instituto Tecnológico Metropolitano": "Instituto Tecnológico Metropolitano (ITM)",
    "Luteran University of Brazil": "Universidade Luterana do Brasil (ULBRA)",
    "PUC - Rio": "Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio)",
    "PUC MINAS": "Pontifícia Universidade Católica de Minas Gerais (PUC Minas)",
    "PUC Minas": "Pontifícia Universidade Católica de Minas Gerais (PUC Minas)",
    "PUC-MG - Pontifícia Universidade Católica de Minas Gerais": "Pontifícia Universidade Católica de Minas Gerais (PUC Minas)",
    "PUC-Rio": "Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio)",
    "PUCRS": "Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)",
    "Pontificia Universidad Católica de Valparaíso": "Pontificia Universidad Católica de Valparaíso (PUCV)",
    "Pontificia Universidade Catolica do Rio Grande do Sul - PUCRS": "Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)",
    "Pontifícia Universidade Católica de Minas Gerais": "Pontifícia Universidade Católica de Minas Gerais (PUC Minas)",
    "Pontífica Universidade Católica do Rio Grande do Sul": "Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)",
    "Programa de Engenharia de Sistemas e Computação - COPPE/UFRJ": "Universidade Federal do Rio de Janeiro (UFRJ)",
    "Salvador University IFBA": "Universidade Salvador (UNIFACS)",
    "State University of Londrina (UEL)": "Universidade Estadual de Londrina (UEL)",
    "São Paulo State University (UNESP)": "Universidade Estadual Paulista (UNESP)",
    "UCPEL and UFPEL": "Universidade Católica de Pelotas (UCPel) / Universidade Federal de Pelotas (UFPel)",
    "UEPB": "Universidade Estadual da Paraíba (UEPB)",
    "UESC": "Universidade Estadual de Santa Cruz (UESC)",
    "UESPI": "Universidade Estadual do Piauí (UESPI)",
    "UFBA": "Universidade Federal da Bahia (UFBA)",
    "UFBA - Universidade Federal da Bahia": "Universidade Federal da Bahia (UFBA)",
    "UFERSA": "Universidade Federal Rural do Semi-Árido (UFERSA)",
    "UFERSA - -- Select Country": "Universidade Federal Rural do Semi-Árido (UFERSA)",
    "UFES - Universidade Federal do Espírito Santo": "Universidade Federal do Espírito Santo (UFES)",
    "UFJF": "Universidade Federal de Juiz de Fora (UFJF)",
    "UFLA": "Universidade Federal de Lavras (UFLA)",
    "UFMG": "Universidade Federal de Minas Gerais (UFMG)",
    "UFPA": "Universidade Federal do Pará (UFPA)",
    "UFPel": "Universidade Federal de Pelotas (UFPel)",
    "UFRGS- Universidade Federal Rio Grande do Sul": "Universidade Federal do Rio Grande do Sul (UFRGS)",
    "UFRJ": "Universidade Federal do Rio de Janeiro (UFRJ)",
    "UFRN": "Universidade Federal do Rio Grande do Norte (UFRN)",
    "UFRN - Universidade Federal do Rio Grande do Norte": "Universidade Federal do Rio Grande do Norte (UFRN)",
    "UFRN / UFERSA": "Universidade Federal do Rio Grande do Norte (UFRN) / Universidade Federal Rural do Semi-Árido (UFERSA)",
    "UFRRJ": "Universidade Federal Rural do Rio de Janeiro (UFRRJ)",
    "UFSC": "Universidade Federal de Santa Catarina (UFSC)",
    "UFSC - Universidade Federal de Santa Catarina": "Universidade Federal de Santa Catarina (UFSC)",
    "UFSJ - -- Select Country": "Universidade Federal de São João del-Rei (UFSJ)",
    "UNIFESP": "Universidade Federal de São Paulo (UNIFESP)",
    "UNIFTEC": "Centro Universitário UNIFTEC (UNIFTEC)",
    "UNINORTE": "Centro Universitário do Norte (UNINORTE)",
    "UNISINOS": "Universidade do Vale do Rio dos Sinos (UNISINOS)",
    "Univerdade Federal do Amazonas": "Universidade Federal do Amazonas (UFAM)",
    "UNIVERSIDADE DO ESTADO DO AMAZONAS": "Universidade do Estado do Amazonas (UEA)",
    "UNIVERSIDADE ESTADUAL DE CAMPINAS (UNICAMP)": "Universidade Estadual de Campinas (UNICAMP)",
    "UNIVERSIDADE FEDERAL DE UBERLANDIA": "Universidade Federal de Uberlândia (UFU)",
    "UNIVERSIDADE FEDERAL DO PARÁ": "Universidade Federal do Pará (UFPA)",
    "UPF": "Universidade de Passo Fundo (UPF)",
    "USP - Universidade de São Paulo": "Universidade de São Paulo (USP)",
    "USP-SC": "Universidade de São Paulo (USP)",
    "UTFPR": "Universidade Tecnológica Federal do Paraná (UTFPR)",
    "Unifacs": "Universidade Salvador (UNIFACS)",
    "Unifebe": "Centro Universitário de Brusque (UNIFEBE)",
    "Unifesp": "Universidade Federal de São Paulo (UNIFESP)",
    "Uniftec": "Centro Universitário UNIFTEC (UNIFTEC)",
    "Uninorte Laureate International Universities": "Centro Universitário do Norte (UNINORTE)",
    "Uninorte Laureate Universities": "Centro Universitário do Norte (UNINORTE)",
    "Unisinos": "Universidade do Vale do Rio dos Sinos (UNISINOS)",
    "Universidad Nacional de Colombia": "Universidad Nacional de Colombia (UNAL)",
    "Universidad Nacional de Colombia - Sede Manizales": "Universidad Nacional de Colombia (UNAL)",
    "Universidad Nacional de Colombia - Sede Medellin": "Universidad Nacional de Colombia (UNAL)",
    "Universidad Nacional de Colombia - Sede Medellín": "Universidad Nacional de Colombia (UNAL)",
    "Universidad de Valparaiso": "Universidad de Valparaíso (UV)",
    "Universidad de Valparaíso": "Universidad de Valparaíso (UV)",
    "Universidade Católica de Brasília": "Universidade Católica de Brasília (UCB)",
    "Universidade Estadual da Paraíba": "Universidade Estadual da Paraíba (UEPB)",
    "Universidade Estadual de Feira de Santana": "Universidade Estadual de Feira de Santana (UEFS)",
    "Universidade Estadual de Santa Cruz": "Universidade Estadual de Santa Cruz (UESC)",
    "Universidade Estadual do Ceará": "Universidade Estadual do Ceará (UECE)",
    "Universidade Estadual do Piauí": "Universidade Estadual do Piauí (UESPI)",
    "Universidade Federal Rural de Pernambuco": "Universidade Federal Rural de Pernambuco (UFRPE)",
    "Universidade Federal Rural do Rio de Janeiro": "Universidade Federal Rural do Rio de Janeiro (UFRRJ)",
    "Universidade Federal Rural do Semi-Árido": "Universidade Federal Rural do Semi-Árido (UFERSA)",
    "Universidade Federal da Bahia": "Universidade Federal da Bahia (UFBA)",
    "Universidade Federal da Bahia - UFBA": "Universidade Federal da Bahia (UFBA)",
    "Universidade Federal da Fronteira Sul - UFFS": "Universidade Federal da Fronteira Sul (UFFS)",
    "Universidade Federal de Goiás": "Universidade Federal de Goiás (UFG)",
    "Universidade Federal de Goiás - Ciências da Computação - Campus Jataí": "Universidade Federal de Goiás (UFG)",
    "Universidade Federal de Goiás - UFG": "Universidade Federal de Goiás (UFG)",
    "Universidade Federal de Juiz de Fora": "Universidade Federal de Juiz de Fora (UFJF)",
    "Universidade Federal de Lavras": "Universidade Federal de Lavras (UFLA)",
    "Universidade Federal de Minas Gerais": "Universidade Federal de Minas Gerais (UFMG)",
    "Universidade Federal de Ouro Preto": "Universidade Federal de Ouro Preto (UFOP)",
    "Universidade Federal de Pelotas": "Universidade Federal de Pelotas (UFPel)",
    "Universidade Federal de Santa Catarina": "Universidade Federal de Santa Catarina (UFSC)",
    "Universidade Federal de Santa Catarina - Campus Araranguá": "Universidade Federal de Santa Catarina (UFSC)",
    "Universidade Federal de São Carlos": "Universidade Federal de São Carlos (UFSCar)",
    "Universidade Federal de São João Del Rei": "Universidade Federal de São João del-Rei (UFSJ)",
    "Universidade Federal de São João Del-Rei": "Universidade Federal de São João del-Rei (UFSJ)",
    "Universidade Federal de São João del Rei": "Universidade Federal de São João del-Rei (UFSJ)",
    "Universidade Federal de São Paulo": "Universidade Federal de São Paulo (UNIFESP)",
    "Universidade Federal de São Paulo - UNIFESP": "Universidade Federal de São Paulo (UNIFESP)",
    "Universidade Federal de Uberlandia": "Universidade Federal de Uberlândia (UFU)",
    "Universidade Federal do Ceara": "Universidade Federal do Ceará (UFC)",
    "Universidade Federal do Espirito Santo - UFES": "Universidade Federal do Espírito Santo (UFES)",
    "Universidade Federal do Espírito Santo": "Universidade Federal do Espírito Santo (UFES)",
    "Universidade Federal do Espírito Santo - UFES": "Universidade Federal do Espírito Santo (UFES)",
    "Universidade Federal do Maranhão": "Universidade Federal do Maranhão (UFMA)",
    "Universidade Federal do Maranhão - UFMA": "Universidade Federal do Maranhão (UFMA)",
    "Universidade Federal do Oeste do Pará": "Universidade Federal do Oeste do Pará (UFOPA)",
    "Universidade Federal do Pampa": "Universidade Federal do Pampa (UNIPAMPA)",
    "Universidade Federal do Pará": "Universidade Federal do Pará (UFPA)",
    "Universidade Federal do Rio Grande": "Universidade Federal do Rio Grande (FURG)",
    "Universidade Federal do Rio Grande do Norte": "Universidade Federal do Rio Grande do Norte (UFRN)",
    "Universidade Federal do Rio de Janeiro": "Universidade Federal do Rio de Janeiro (UFRJ)",
    "Universidade Federal do Sul e Sudeste do Pará": "Universidade Federal do Sul e Sudeste do Pará (UNIFESSPA)",
    "Universidade Federal do Vale do São Francisco": "Universidade Federal do Vale do São Francisco (UNIVASF)",
    "Universidade Federal dos Vales do Jequitinhonha & Mucuri": "Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM)",
    "Universidade Federal dos Vales do Jequitinhonha e Mucuri": "Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM)",
    "Universidade Regional Integrada Do Alto Uruguai E Das Missões": "Universidade Regional Integrada do Alto Uruguai e das Missões (URI)",
    "Universidade Regional Integrada do Alto Uruguai e das Missões": "Universidade Regional Integrada do Alto Uruguai e das Missões (URI)",
    "Universidade Regional Integrada do Alto Uruguai e das Missões - URI Erechim": "Universidade Regional Integrada do Alto Uruguai e das Missões (URI)",
    "Universidade Salvador": "Universidade Salvador (UNIFACS)",
    "Universidade Tecnológica Federal do Paraná": "Universidade Tecnológica Federal do Paraná (UTFPR)",
    "Universidade Tecnológica Federal do Paraná / Universidade Federal do Paraná": "Universidade Tecnológica Federal do Paraná (UTFPR) / Universidade Federal do Paraná (UFPR)",
    "Universidade Tecnológica Federal do Paraná Campus Guarapuava (UTFPR-GP)": "Universidade Tecnológica Federal do Paraná (UTFPR)",
    "Universidade de Brasília": "Universidade de Brasília (UnB)",
    "Universidade de Passo Fundo": "Universidade de Passo Fundo (UPF)",
    "Universidade de Patos de Minas": "Universidade de Patos de Minas (UNIPAM)",
    "Universidade de Pernambuco": "Universidade de Pernambuco (UPE)",
    "Universidade de São Paulo (ICMC - USP)": "Universidade de São Paulo (USP)",
    "Universidade do Estado da Bahia/Faculdade de Ciências Aplicadas e Sociais de Petrolina": "Universidade do Estado da Bahia (UNEB) / Faculdade de Ciências Aplicadas e Sociais de Petrolina (FACAPE)",
    "Universidade do Estado de Minas Gerais": "Universidade do Estado de Minas Gerais (UEMG)",
    "Universidade do Estado do Amazonas": "Universidade do Estado do Amazonas (UEA)",
    "Universidade do Estado do Amazonas - UEA": "Universidade do Estado do Amazonas (UEA)",
    "Universidade do Estado do Rio Grande do Norte": "Universidade do Estado do Rio Grande do Norte (UERN)",
    "Universidade do Estado do Rio Grande do Norte - UERN": "Universidade do Estado do Rio Grande do Norte (UERN)",
    "Universidade do Porto": "Universidade do Porto (U.Porto)",
    "Universidade do Vale do Itajaí": "Universidade do Vale do Itajaí (UNIVALI)",
    "Universidade do Vale dos Sinos - UNISINOS": "Universidade do Vale do Rio dos Sinos (UNISINOS)",
    "University Federal Rural of Pernambuco - UFRPE": "Universidade Federal Rural de Pernambuco (UFRPE)",
    "University of Amazonas": "Universidade Federal do Amazonas (UFAM)",
    "University of Campinas": "Universidade Estadual de Campinas (UNICAMP)",
    "University of Fortaleza": "Universidade de Fortaleza (UNIFOR)",
    "University of Pernambuco": "Universidade de Pernambuco (UPE)",
    "University of Porto": "Universidade do Porto (U.Porto)",
    "University of São Paulo": "Universidade de São Paulo (USP)",
    "eliane.kormann@unifebe.edu.br - -- Select Country": "Centro Universitário de Brusque (UNIFEBE)",
    "l'Université Nice Sophia-Antipolis LAPCOS França": "Université Nice Sophia Antipolis (UNS)",
    "rosana@unifebe.edu.br - -- Select Country": "Centro Universitário de Brusque (UNIFEBE)",
    "Instituto Federal Goiano": "Instituto Federal Goiano (IF Goiano)",
    "Instituto Federal Goiano - IF Goiano": "Instituto Federal Goiano (IF Goiano)",
    "Instituto Federal Sudeste de MG": "Instituto Federal do Sudeste de Minas Gerais (IF Sudeste MG)",
    "Instituto Federal Sudeste de MG - Cataguases": "Instituto Federal do Sudeste de Minas Gerais (IF Sudeste MG)",
    "Instituto Federal Sul-Riograndense": "Instituto Federal Sul-rio-grandense (IFSul)",
    "Instituto Federal Sul-rio-grandense": "Instituto Federal Sul-rio-grandense (IFSul)",
    "Instituto Federal de Brasília": "Instituto Federal de Brasília (IFB)",
    "Instituto Federal de Ciência e Tecnologia do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "Instituto Federal de Educação Ciência e Tecnologia Goiano": "Instituto Federal Goiano (IF Goiano)",
    "Instituto Federal de Educação Ciência e Tecnologia do Acre": "Instituto Federal do Acre (IFAC)",
    "Instituto Federal de Educação Ciência e Tecnologia do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "Instituto Federal de Educação Ciência e Tecnologia do Maranhão - IFMA": "Instituto Federal de Educação Ciência e Tecnologia do Maranhão (IFMA)",
    "Instituto Federal de Educação Ciência e Tecnologia do Maranhão - IFMA (Campus Caxias)": "Instituto Federal de Educação Ciência e Tecnologia do Maranhão (IFMA)",
    "Instituto Federal de Educação Ciência e Tecnologia do Norte de Minas Gerais": "Instituto Federal de Educação Ciência e Tecnologia do Norte de Minas Gerais (IFNMG)",
    "Instituto Federal de Educação Ciência e Tecnologia do RS": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte (IFRN)": "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte (IFRN)",
    "Instituto Federal de Educação Ciência e Tecnologia do Sul de Minas Gerais": "Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais (IFSULDEMINAS)",
    "Instituto Federal de Educação Ciência e Tecnologia do Sul de Minas Gerais - IFSULDEMINAS": "Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais (IFSULDEMINAS)",
    "Instituto Federal de Educação Ciência e Tecnologia do Sul de Minas Gerais (IFSULDEMINAS)": "Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais (IFSULDEMINAS)",
    "Instituto Federal de Educação Ciência e Tecnologia do Sul de Minas Gerais (IFSULMINAS)": "Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais (IFSULDEMINAS)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Amazonas - Campus Parintins": "Instituto Federal do Amazonas (IFAM)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Amazonas - IFAM Campus Parintins": "Instituto Federal do Amazonas (IFAM)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Maranhão - IFMA": "Instituto Federal de Educação Ciência e Tecnologia do Maranhão (IFMA)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte": "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte (IFRN)",
    "Instituto Federal de Educação, Ciência e Tecnologia do Sertão Pernambucano - Campus Petrolina-PE": "Instituto Federal do Sertão Pernambucano (IFSertãoPE)",
    "Instituto Federal de Pernambuco": "Instituto Federal de Pernambuco (IFPE)",
    "Instituto Federal de Rondônia - IFRO": "Instituto Federal de Rondônia (IFRO)",
    "Instituto Federal do Ceará": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "Instituto Federal do Ceará - -- Select Country": "Instituto Federal de Educação Ciência e Tecnologia do Ceará (IFCE)",
    "Instituto Federal do Espírito Santo": "Instituto Federal do Espírito Santo (IFES)",
    "Instituto Federal do Rio Grande do Norte": "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte (IFRN)",
    "Instituto Federal do Rio Grande do Norte- Campus Ipanguaçu": "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte (IFRN)",
    "Instituto Federal do Rio Grande do Sul": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "Instituto Federal do Rio Grande do Sul - Campus Porto Alegre": "Instituto Federal do Rio Grande do Sul (IFRS)",
    "Instituto Federal do Sertão Pernambucano": "Instituto Federal do Sertão Pernambucano (IFSertãoPE)",
    "Instituto Federal do Sertão Pernambucano - IFSertão": "Instituto Federal do Sertão Pernambucano (IFSertãoPE)",
    "Instituto Federal do Sertão Pernambucano - IFSertão Campus Petrolina": "Instituto Federal do Sertão Pernambucano (IFSertãoPE)",
}


ENGLISH_EXACT = {
    "-": "",
    "Aix-Marseille Université": "Aix-Marseille University",
    "Antonio Meneghetti Faculdade": "Antonio Meneghetti College",
    "Centro Federal de Educação Tecnológica Celso Suckow da Fonseca": "Celso Suckow da Fonseca Federal Center for Technological Education",
    "Centro Federal de Educação Tecnológica de Minas Gerais": "Federal Center for Technological Education of Minas Gerais",
    "Centro Universitário Maurício de Nassau": "Mauricio de Nassau University Center",
    "Centro Universitário UNIFTEC": "UNIFTEC University Center",
    "Centro Universitário de Brusque": "Brusque University Center",
    "Centro Universitário do Norte": "University Center of the North",
    "Comunicar e Dizer": "Comunicar e Dizer",
    "Descomplica.me": "Descomplica.me",
    "FSV": "Vale do Salgado College",
    "FVS - Faculdade Vale do Salgado": "Vale do Salgado College",
    "Faculdade Regional do Centro Sul de Sergipe": "Regional College of South-Central Sergipe",
    "Faculdade São Miguel": "Sao Miguel College",
    "Faculdade Vale do Salgado": "Vale do Salgado College",
    "Faculdade Vale do Salgado - -- Select Country": "Vale do Salgado College",
    "Faculdade de Tecnologia de Taquaritinga": "Taquaritinga College of Technology",
    "Faculdades Unificadas de Cataguases": "Integrated Colleges of Cataguases",
    "Faculdades Unificadas de Cataguases(Doctum)": "Doctum Integrated Colleges of Cataguases",
    "Florida Institute of Technology": "Florida Institute of Technology",
    "Fundação Paulo Feitoza": "Paulo Feitoza Foundation",
    "Fundação Universidade do Rio Grande": "Federal University of Rio Grande Foundation",
    "Harvard University": "Harvard University",
    "Instituto Atlântico": "Atlantico Institute",
    "Instituto Federal Goiano": "Goiano Federal Institute",
    "Instituto Federal Sul-rio-grandense": "Sul-rio-grandense Federal Institute",
    "Instituto Federal de Alagoas": "Federal Institute of Alagoas",
    "Instituto Federal de Brasília": "Federal Institute of Brasilia",
    "Instituto Federal de Educação Ciência e Tecnologia do Ceará": "Federal Institute of Education, Science and Technology of Ceara",
    "Instituto Federal de Educação Ciência e Tecnologia do Maranhão": "Federal Institute of Education, Science and Technology of Maranhao",
    "Instituto Federal de Educação Ciência e Tecnologia do Norte de Minas Gerais": "Federal Institute of Education, Science and Technology of Northern Minas Gerais",
    "Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte": "Federal Institute of Education, Science and Technology of Rio Grande do Norte",
    "Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais": "Federal Institute of Education, Science and Technology of Southern Minas Gerais",
    "Instituto Federal de Pernambuco": "Federal Institute of Pernambuco",
    "Instituto Federal de Rondônia": "Federal Institute of Rondonia",
    "Instituto Federal de Sergipe": "Federal Institute of Sergipe",
    "Instituto Federal do Acre": "Federal Institute of Acre",
    "Instituto Federal do Amazonas": "Federal Institute of Amazonas",
    "Instituto Federal do Espírito Santo": "Federal Institute of Espirito Santo",
    "Instituto Federal do Paraná": "Federal Institute of Parana",
    "Instituto Federal do Rio Grande do Sul": "Federal Institute of Rio Grande do Sul",
    "Instituto Federal do Sertão Pernambucano": "Federal Institute of the Pernambuco Hinterland",
    "Instituto Federal do Sudeste de Minas Gerais": "Federal Institute of Southeastern Minas Gerais",
    "Instituto Nacional de Educação de Surdos": "National Institute for the Education of the Deaf",
    "Instituto Tecnológico Metropolitano": "Metropolitan Technological Institute",
    "Instituto Tecnológico de Aeronáutica": "Aeronautics Institute of Technology",
    "Ministério Público da Paraíba": "Public Prosecutor's Office of Paraiba",
    "Multivix": "Multivix",
    "Multivix Vitória": "Multivix Vitoria",
    "PREFEITURA - SECRETARIA DE EDUCAÇÃO - Santa Quitéria": "Santa Quiteria City Hall - Department of Education",
    "Pontificia Universidad Católica de Valparaíso": "Pontifical Catholic University of Valparaiso",
    "Pontifícia Universidade Católica de Minas Gerais": "Pontifical Catholic University of Minas Gerais",
    "Pontifícia Universidade Católica do Rio Grande do Sul": "Pontifical Catholic University of Rio Grande do Sul",
    "Pontifícia Universidade Católica do Rio de Janeiro": "Pontifical Catholic University of Rio de Janeiro",
    "Positivo": "Positivo",
    "Prefeitura Municipal de Igarassu": "Igarassu City Hall",
    "Serviço Nacional de Aprendizagem Comercial - Senac/RS": "National Commercial Training Service of Rio Grande do Sul",
    "Serviço Nacional de Aprendizagem Comercial - SenacRS": "National Commercial Training Service of Rio Grande do Sul",
    "Secretaria de Educação de Amparo-SP": "Department of Education of Amparo, SP",
    "Secretaria de Educação do Município de Amparo SP": "Department of Education of the Municipality of Amparo, SP",
    "Unidade de Ensino Superior Dom Bosco": "Dom Bosco Higher Education Unit",
    "Universidad Nacional de Colombia": "National University of Colombia",
    "Universidad de Valparaíso": "University of Valparaiso",
    "Universidade Católica de Brasília": "Catholic University of Brasilia",
    "Universidade Católica de Pelotas / Universidade Federal de Pelotas": "Catholic University of Pelotas / Federal University of Pelotas",
    "Universidade Estadual Paulista": "Sao Paulo State University",
    "Universidade Estadual da Paraíba": "State University of Paraiba",
    "Universidade Estadual de Campinas": "State University of Campinas",
    "Universidade Estadual de Feira de Santana": "State University of Feira de Santana",
    "Universidade Estadual de Londrina": "State University of Londrina",
    "Universidade Estadual de Santa Cruz": "State University of Santa Cruz",
    "Universidade Estadual do Ceará": "State University of Ceara",
    "Universidade Estadual do Piauí": "State University of Piaui",
    "Universidade Federal Rural de Pernambuco": "Federal Rural University of Pernambuco",
    "Universidade Federal Rural do Rio de Janeiro": "Federal Rural University of Rio de Janeiro",
    "Universidade Federal Rural do Semi-Árido": "Federal Rural University of the Semi-Arid Region",
    "Universidade Federal da Bahia": "Federal University of Bahia",
    "Universidade Federal da Fronteira Sul": "Federal University of the Southern Frontier",
    "Universidade Federal da Paraíba": "Federal University of Paraiba",
    "Universidade Federal de Alagoas": "Federal University of Alagoas",
    "Universidade Federal de Campina Grande": "Federal University of Campina Grande",
    "Universidade Federal de Goiás": "Federal University of Goias",
    "Universidade Federal de Juiz de Fora": "Federal University of Juiz de Fora",
    "Universidade Federal de Lavras": "Federal University of Lavras",
    "Universidade Federal de Minas Gerais": "Federal University of Minas Gerais",
    "Universidade Federal de Ouro Preto": "Federal University of Ouro Preto",
    "Universidade Federal de Pelotas": "Federal University of Pelotas",
    "Universidade Federal de Pernambuco": "Federal University of Pernambuco",
    "Universidade Federal de Santa Catarina": "Federal University of Santa Catarina",
    "Universidade Federal de Santa Maria": "Federal University of Santa Maria",
    "Universidade Federal de Sergipe": "Federal University of Sergipe",
    "Universidade Federal de São Carlos": "Federal University of Sao Carlos",
    "Universidade Federal de São João del-Rei": "Federal University of Sao Joao del-Rei",
    "Universidade Federal de São Paulo": "Federal University of Sao Paulo",
    "Universidade Federal de Uberlândia": "Federal University of Uberlandia",
    "Universidade Federal do ABC": "Federal University of ABC",
    "Universidade Federal do Amazonas": "Federal University of Amazonas",
    "Universidade Federal do Ceará": "Federal University of Ceara",
    "Universidade Federal do Espírito Santo": "Federal University of Espirito Santo",
    "Universidade Federal do Estado do Rio de Janeiro": "Federal University of the State of Rio de Janeiro",
    "Universidade Federal do Maranhão": "Federal University of Maranhao",
    "Universidade Federal do Oeste do Pará": "Federal University of Western Para",
    "Universidade Federal do Pampa": "Federal University of Pampa",
    "Universidade Federal do Paraná": "Federal University of Parana",
    "Universidade Federal do Pará": "Federal University of Para",
    "Universidade Federal do Rio Grande": "Federal University of Rio Grande",
    "Universidade Federal do Rio Grande do Norte": "Federal University of Rio Grande do Norte",
    "Universidade Federal do Rio Grande do Norte / Universidade Federal Rural do Semi-Árido": "Federal University of Rio Grande do Norte / Federal Rural University of the Semi-Arid Region",
    "Universidade Federal do Rio Grande do Sul": "Federal University of Rio Grande do Sul",
    "Universidade Federal do Rio de Janeiro": "Federal University of Rio de Janeiro",
    "Universidade Federal do Sul e Sudeste do Pará": "Federal University of the South and Southeast of Para",
    "Universidade Federal do Vale do São Francisco": "Federal University of the Sao Francisco Valley",
    "Universidade Federal dos Vales do Jequitinhonha e Mucuri": "Federal University of the Jequitinhonha and Mucuri Valleys",
    "Universidade Luterana do Brasil": "Lutheran University of Brazil",
    "Universidade Regional Integrada do Alto Uruguai e das Missões": "Integrated Regional University of Upper Uruguay and the Missions",
    "Universidade Salvador": "Salvador University",
    "Universidade Tecnológica Federal do Paraná": "Federal University of Technology - Parana",
    "Universidade Tecnológica Federal do Paraná / Universidade Federal do Paraná": "Federal University of Technology - Parana / Federal University of Parana",
    "Universidade de Brasília": "University of Brasilia",
    "Universidade de Fortaleza": "University of Fortaleza",
    "Universidade de Passo Fundo": "University of Passo Fundo",
    "Universidade de Patos de Minas": "University of Patos de Minas",
    "Universidade de Pernambuco": "University of Pernambuco",
    "Universidade de São Paulo": "University of Sao Paulo",
    "Universidade do Estado da Bahia": "State University of Bahia",
    "Universidade do Estado da Bahia / Faculdade de Ciências Aplicadas e Sociais de Petrolina": "State University of Bahia / College of Applied and Social Sciences of Petrolina",
    "Universidade do Estado de Minas Gerais": "State University of Minas Gerais",
    "Universidade do Estado de Santa Catarina": "State University of Santa Catarina",
    "Universidade do Estado do Amazonas": "State University of Amazonas",
    "Universidade do Estado do Rio Grande do Norte": "State University of Rio Grande do Norte",
    "Universidade do Estado do Rio de Janeiro": "State University of Rio de Janeiro",
    "Universidade do Porto": "University of Porto",
    "Universidade do Vale do Itajaí": "University of Vale do Itajai",
    "Universidade do Vale do Rio dos Sinos": "University of Vale do Rio dos Sinos",
    "Université Nice Sophia Antipolis": "University of Nice Sophia Antipolis",
}


def strip_acronym(value: str) -> str:
    return re.sub(r"\s*\([^)]*\)", "", value).strip()


def affiliation_to_english(value: str) -> str:
    base = strip_acronym(value)
    if base in ENGLISH_EXACT:
        return ENGLISH_EXACT[base]
    return base


def main():
    root = Path(__file__).resolve().parents[1]
    csv_path = root / "output/2018/csv/Autores.csv"

    rows: list[dict[str, str]] = []

    with csv_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter=";")
        for row in reader:
            rows.append(row)

    updated = 0
    updated_en = 0
    for row in rows:
        old_aff = row["authorAffiliation"]
        new_aff = EXACT_REPLACEMENTS.get(old_aff, old_aff)
        if new_aff != old_aff:
            row["authorAffiliation"] = new_aff
            updated += 1

        new_aff_en = affiliation_to_english(row["authorAffiliation"])
        if row["authorAffiliationEn"] != new_aff_en:
            row["authorAffiliationEn"] = new_aff_en
            updated_en += 1

    fieldnames = rows[0].keys() if rows else []
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
            delimiter=";",
            quotechar='"',
            quoting=csv.QUOTE_ALL,
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"Atualizações realizadas em authorAffiliation: {updated}")
    print(f"Atualizações realizadas em authorAffiliationEn: {updated_en}")


if __name__ == "__main__":
    main()

